последняя задача раздела "Компоненты"
js-tasks-ru/vue-20221107_dalahan pull request #4
Opened 2022-11-17 08:12 UTC by DalahanM

2022-11-17 08:12 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-11-17 08:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-11-17 21:20 UTC, ShGKme requested changes
Использование хука `updated` здесь некорректно...

2022-11-17 21:20 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +  },
Пустой объект - не частный случай объекта с описанием митапа. Лучше начальным значением явно указать `null`. Это позволит знать, есть ли митап напрямую, а не косвенно. Например, проверка через `meetup.id` сломается, если будет митап с `id === 0`. 

В других ситуациях это также позволяет сразу увидеть, где нужны проверки на `null`, чтобы не ловить потом более сложно находимые ошибки при обращении к `undefined` полям.

2022-11-17 21:20 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +  },
Хук жизненного цикла `updated` нужен очень редко. Он срабатывает всегда, когда ререндерится компонент (обновляется эта часть страницы). И используется только, когда требуется реагировать на ЛЮБОЕ обновление компонента (редкий случай, например, создание обёрток над легаси или не Vue библиотеками), либо когда требуется реагировать на обновление, не связанное с данными (например, обновление слота).

При таком решении данные будут перезапрашиваться каждый раз, когда происходит что угодно в компоненте. И из-за этого пришлось добавить лишнюю проверку на `this.savId != this.meetupId`.

2022-11-17 21:20 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +      }
Можно хранить в одном свойстве `meetup` сразу всё: и митап, и отсутствие митапа, и ошибку. Но лучше не экономить переменную и не смешивать в одном свойстве всё. Ошибку или её отсутствие хранить в отдельном свойстве. Явно хранить отсутствие митапа. Дополнительно можно хранить состояние или флаг загрузки. 

В противном случае сложно определённо сказать, в каком месте в какой момент времени что на самом деле находится в переменной, какой её тип.

2022-11-17 21:20 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +      }
> // обнуляю только ради прохождения 5го автотеста :(

Так как в вашем решении для индикации загрузки используются сами данные митапа, то после загрузки первого митапа без его обнуления уже невозможно определить, идёт ли какой-то процесс загрузки. Автотест проверяет, что есть индикация загрузки во время загрузки.

2022-11-17 21:20 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +  },
Вместо общего хука жизни компонента требуется отслеживать непосредственно данные, изменение которых приводит к необходимости запрашивать новые данные - отслеживать изменение `meetupId`.

2022-11-18 06:28 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-11-21 10:57 UTC, ShGKme approved these changes
Принято

2022-11-21 10:57 UTC, merged